# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TimerThreadPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TimerThreadPod
  pod 'LJTimerThread', '~> 1.0.2'
  target 'TimerThreadPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TimerThreadPodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
